# Generated by Django 3.2.6 on 2022-03-25 15:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bolsa', '0002_rename_variable_bolsa'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bolsa',
            old_name='name',
            new_name='nombre',
        ),
    ]
